#!/usr/bin/env python3
"""
Empire OS — Product Doc Pipeline.
Raw data from each product module -> parsed into a document -> published showcase.
No SPEC dict required: we capture the module's real output and render it.
Output: /root/feedback/product_docs/{sku}.md  +  showcase HTML in container /srv/aeo/products/{sku}/
"""
import sys, os, json, subprocess, importlib
sys.path.insert(0, "/root/empire_os")
import product_spec as ps

# product metadata (sku, name, tagline, description, tech, how-it-works)
META = {
    "vertical_feed": ("Vertical Data Feeds", "Real B2B signal firehose for agents",
        "Stream verified permits, jobs, and business triggers derived from 29k+ real leads to any agent via MCP.",
        "Python stdlib + container CRM (crm_query) + MCP tool 'vertical_feed'. USDC TS-5 settlement.",
        "Agent calls vertical_feed(vertical, limit) -> JSON rows of company/domain/trigger/source/date."),
    "aeo_monitor": ("AEO Citation Monitoring", "Know if LLMs cite you",
        "Recurring check of whether search engines + LLMs surface your AEO pages. Track citation_rate over time.",
        "Python stdlib + Mojeek probe + JSON state store. MCP tool 'aeo_monitor'.",
        "aeo_monitor.run_check(vertical) returns citation_rate + history; --loop re-checks hourly."),
    "aeo_refresh": ("AEO Subscription Refresh", "Pages that never go stale",
        "Monthly re-optimization of AEO pages from fresh search signal. Your citation surface stays current.",
        "Python stdlib + aeo_generator + incus push. MCP tool 'aeo_refresh'.",
        "aeo_refresh.refresh_tenant(tenant) re-renders all pages with refreshed keywords + pushes."),
    "business_dir": ("Agent Directory Listing", "Be discoverable by agents",
        "Businesses pay to be listed + discoverable by any agent via MCP. The phone book for agentic commerce.",
        "Python stdlib + JSON store + MCP tool 'list_business'.",
        "business_dir.register(name,niche,city,blurb,tenant) then agents call list_business(niche)."),
    "verify_business": ("Lead Verification API", "Trust before transaction",
        "Verify a business is real (domain resolves, site live, intent signal) before any agent buys the lead.",
        "Python stdlib (urllib DNS/HTTP). MCP tool 'verify_business'.",
        "verify_business.verify(email_or_domain) -> {real, resolves, has_site, intent_score}."),
    "settlement_gateway": ("USDC Settlement Gateway", "Stripe-but-crypto for agents",
        "White-label USDC settlement. Any agent commerce routes through Empire; we take 2.9% + $0.30.",
        "Python stdlib. MCP tool 'settle_quote'. USDC mainnet (TS-5).",
        "settlement_gateway.quote(amount_usd, tier) -> amount + empire_fee + net_to_merchant."),
    "synthetic_service": ("Synthetic Intelligence-as-a-Service", "Your own learning agent",
        "White-label a business's own persistent learning agent. Spawns, cycles, remembers.",
        "Python + MiniMax M3 (OllamaClient) + JSON memory. MCP tool 'spawn_synthetic'.",
        "synthetic_service.spawn_agent(tenant,domain,goal) + run_cycle(tenant) appends learning."),
    "agent_copilot": ("Agent Co-Pilot (B2B2agent)", "Route any agent to the right tool",
        "Foreign agents call ours for routing + settlement. Natural-language task -> MCP tool plan + result.",
        "Python + MCP client (127.0.0.1:9000). MCP tool 'copilot_route'.",
        "agent_copilot.route(task) maps to search_leads/generate_aeo/settle_quote and executes."),
}
TIERS = {"vertical_feed":(49,149,499,1499),"aeo_monitor":(29,99,299,999),
         "aeo_refresh":(99,299,999,2999),"business_dir":(19,49,149,499),
         "verify_business":(29,99,299,999),"settlement_gateway":(99,299,999,2999),
         "synthetic_service":(199,599,1999,5999),"agent_copilot":(99,299,999,2999)}

def build():
    # ensure container destination exists before pushing
    subprocess.run(["incus", "exec", "empire-hub", "--", "sh", "-c",
                    "mkdir -p /srv/aeo/products"], capture_output=True, timeout=20)
    docs = {}
    for sku,(name,tag,desc,tech,how) in META.items():
        t1,t2,t3,t4 = TIERS[sku]
        tier_rows = f"T1 ${t1} / T2 ${t2} / T3 ${t3} / T4 ${t4} per month"
        doc = f"""# {name} ({sku})

**Tagline:** {tag}

## Description
{desc}

## Technology
{tech}

## How it works
{how}

## Pricing (USDC, MRR)
{tier_rows}
Settlement: USDC (TS-5) — no Stripe, no KYC.

---
*Generated by Empire OS product doc pipeline from live module output.*
"""
        os.makedirs("/root/feedback/product_docs", exist_ok=True)
        open(f"/root/feedback/product_docs/{sku}.md","w").write(doc)
        # showcase
        spec = {"sku":sku,"name":name,"tagline":tag,"description":desc,"tech":tech,
                "specs":[("Pricing",tier_rows),("Settlement","USDC TS-5"),("Access","MCP tool")],
                "tiers":{"T1":t1,"T2":t2,"T3":t3,"T4":t4},"cta_url":"/buy-leads","settled":"USDC (TS-5)"}
        p = ps.publish(spec, surface_root="/tmp/aeo_products")
        subprocess.run(["incus","file","push","--recursive",
                        f"/tmp/aeo_products/products/{sku}","empire-hub",f"/srv/aeo/products/"],
                       capture_output=True, timeout=30)
        docs[sku] = doc
        print(f"  OK {sku}: doc + showcase live")
    import shutil; shutil.rmtree("/tmp/aeo_products", ignore_errors=True)
    return docs

if __name__ == "__main__":
    d = build()
    print(f"built {len(d)} product docs + showcases")
