[Service]
Environment=SOLANA_RPC_URL=https://mainnet.helius-rpc.com/?api-key=f8b15d20-84cf-4fed-965a-2b3fe1a62991
Environment=SOLANA_VAULT_WALLET=egJ1t9NZkDs8FvMbfnQTqXzC4KNuhAc9XSfpG9y9AZM
Environment=USDC_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
Environment=HUB_URL=http://127.0.0.1:8081