from pathlib import Path

from test_empiredb_materializer_bootstrap import execute

MIGRATION = Path(
    "migrations/empiredb/024_outbound_provider_event_ingest.sql"
)


def bootstrap(execute):
    execute("postgres", "CREATE DATABASE empiredb;")

    execute("empiredb", r"""
CREATE ROLE empiredb_migrator NOLOGIN;
CREATE ROLE empiredb_app NOLOGIN;
CREATE ROLE empire_outbound_approver NOLOGIN;
CREATE ROLE empire_outbound_sender NOLOGIN;
CREATE ROLE empire_reply_ingest NOLOGIN NOINHERIT;

GRANT USAGE, CREATE ON SCHEMA public TO empiredb_migrator;
GRANT USAGE ON SCHEMA public TO empire_reply_ingest;

SET ROLE empiredb_migrator;

CREATE TABLE public.outbound_intents(
    id uuid PRIMARY KEY,
    normalized_recipient text NOT NULL,
    status text NOT NULL,
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.outbound_events(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id uuid NOT NULL,
    event_type text NOT NULL,
    actor text NOT NULL,
    provider_message_id text,
    payload jsonb DEFAULT '{}'::jsonb,
    occurred_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.outbound_suppressions(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_contact text UNIQUE NOT NULL,
    contact_type text NOT NULL,
    reason text NOT NULL,
    source text NOT NULL,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.outbound_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_suppressions ENABLE ROW LEVEL SECURITY;

GRANT SELECT,UPDATE ON public.outbound_intents
TO empire_reply_ingest;

GRANT INSERT ON public.outbound_events
TO empire_reply_ingest;

GRANT SELECT,INSERT ON public.outbound_suppressions
TO empire_reply_ingest;

GRANT USAGE,SELECT ON SEQUENCE public.outbound_events_id_seq
TO empire_reply_ingest;

GRANT USAGE,SELECT ON SEQUENCE public.outbound_suppressions_id_seq
TO empire_reply_ingest;

CREATE POLICY outbound_intents_empire_reply_ingest_select
ON public.outbound_intents
FOR SELECT TO empire_reply_ingest
USING (true);

CREATE POLICY outbound_intents_empire_reply_ingest_update
ON public.outbound_intents
FOR UPDATE TO empire_reply_ingest
USING (true)
WITH CHECK (true);

CREATE POLICY outbound_events_empire_reply_ingest_insert
ON public.outbound_events
FOR INSERT TO empire_reply_ingest
WITH CHECK (true);

CREATE POLICY outbound_suppressions_empire_reply_ingest_select
ON public.outbound_suppressions
FOR SELECT TO empire_reply_ingest
USING (true);

CREATE POLICY outbound_suppressions_empire_reply_ingest_insert
ON public.outbound_suppressions
FOR INSERT TO empire_reply_ingest
WITH CHECK (true);

RESET ROLE;
""")

    execute("empiredb", MIGRATION.read_text())
    execute("empiredb", MIGRATION.read_text())


def test_provider_event_boundary_and_semantics(execute):
    bootstrap(execute)

    execute("empiredb", r"""
SET ROLE empiredb_migrator;

INSERT INTO public.outbound_intents(
    id,normalized_recipient,status
)
VALUES
(
 '00000000-0000-0000-0000-000000000001',
 'buyer@example.com',
 'sent'
),
(
 '00000000-0000-0000-0000-000000000002',
 'bounce@example.com',
 'sent'
);

RESET ROLE;
""")

    execute("empiredb", r"""
SET ROLE empire_reply_ingest;

SELECT public.record_outbound_provider_event(
 '00000000-0000-0000-0000-000000000001',
 'delivered',
 'msg-delivered',
 'buyer@example.com',
 false,
 '{}'::jsonb
);

SELECT public.record_outbound_provider_event(
 '00000000-0000-0000-0000-000000000001',
 'delivered',
 'msg-delivered',
 'buyer@example.com',
 false,
 '{}'::jsonb
);

SELECT public.record_outbound_provider_event(
 '00000000-0000-0000-0000-000000000002',
 'bounced',
 'msg-bounce',
 'bounce@example.com',
 true,
 '{}'::jsonb
);
""")

    execute(
        "empiredb",
        r"""
SET ROLE empire_reply_ingest;

SELECT public.record_outbound_provider_event(
 '00000000-0000-0000-0000-000000000001',
 'delivered',
 'wrong-recipient',
 'wrong@example.com',
 false,
 '{}'::jsonb
);
""",
        expected_error="provider event recipient mismatch",
    )

    execute(
        "empiredb",
        r"""
SET ROLE empiredb_app;

SELECT public.record_outbound_provider_event(
 '00000000-0000-0000-0000-000000000001',
 'opened',
 'unauthorized',
 'buyer@example.com',
 false,
 '{}'::jsonb
);
""",
        expected_error="permission denied for function record_outbound_provider_event",
    )


def test_provider_event_security_contract(execute):
    bootstrap(execute)

    execute("empiredb", r"""
DO $$
BEGIN
    IF NOT has_table_privilege(
        'empire_reply_ingest',
        'public.outbound_events',
        'SELECT'
    ) THEN
        RAISE EXCEPTION 'reply ingest lacks outbound_events SELECT';
    END IF;

    IF has_function_privilege(
        'empiredb_app',
        'public.record_outbound_provider_event(uuid,text,text,text,boolean,jsonb)',
        'EXECUTE'
    ) THEN
        RAISE EXCEPTION 'generic app has provider-event EXECUTE';
    END IF;

    IF NOT has_function_privilege(
        'empire_reply_ingest',
        'public.record_outbound_provider_event(uuid,text,text,text,boolean,jsonb)',
        'EXECUTE'
    ) THEN
        RAISE EXCEPTION 'reply ingest lacks provider-event EXECUTE';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid=p.pronamespace
        WHERE n.nspname='public'
          AND p.proname='record_outbound_provider_event'
          AND p.prosecdef
    ) THEN
        RAISE EXCEPTION 'provider event RPC must remain SECURITY INVOKER';
    END IF;
END $$;
""")
