#!/usr/bin/env python3
"""
audit_report.py — Branded PDF generator for free + deep audits.
Uses Jinja2 + WeasyPrint. Pure Python, no external service.
"""
from __future__ import annotations

import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional

try:
    from jinja2 import Environment, FileSystemLoader, select_autoescape
except ImportError:
    raise ImportError("pip install jinja2")

try:
    from weasyprint import HTML, CSS
except ImportError:
    raise ImportError("pip install weasyprint  # also needs: apt install -y python3-cairo libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev")

TEMPLATE_DIR = Path(__file__).parent / "templates" / "audit"
TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)

# Default template written on first run
DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ grade }} — {{ niche|title }} SEO Audit for {{ url }}</title>
<style>
  @page { size: A4; margin: 2cm; }
  body { font-family: "DejaVu Sans", "Helvetica", Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a1a; }
  .header { text-align: center; border-bottom: 3px solid #0a3d62; padding-bottom: 1rem; margin-bottom: 2rem; }
  .header h1 { margin: 0; color: #0a3d62; font-size: 24pt; }
  .header .meta { color: #666; font-size: 10pt; margin-top: 0.5rem; }
  .score-box { display: inline-block; background: {{ score_color }}; color: white; padding: 1rem 2rem; border-radius: 8px; font-size: 28pt; font-weight: bold; margin: 1rem 0; }
  .grade {{ font-size: 14pt; opacity: 0.9; }}
  section { margin-bottom: 2rem; page-break-inside: avoid; }
  h2 { color: #0a3d62; border-bottom: 1px solid #ddd; padding-bottom: 0.3rem; font-size: 14pt; }
  .check-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0.5rem; margin: 1rem 0; }
  .check-item { padding: 0.5rem; background: #f8f9fa; border-radius: 4px; }
  .check-label { font-weight: bold; color: #333; }
  .check-value { color: #0a3d62; }
  .fix { background: #fff3cd; border-left: 4px solid #ffc107; padding: 1rem; margin: 1rem 0; border-radius: 0 4px 4px 0; }
  .fix h3 { margin-top: 0; color: #856404; font-size: 11pt; }
  .fix ol { margin: 0.5rem 0 0 1.5rem; }
  .footer { text-align: center; color: #999; font-size: 8pt; border-top: 1px solid #eee; padding-top: 1rem; margin-top: 2rem; }
  .logo { font-weight: bold; color: #0a3d62; }
</style>
</head>
<body>
<div class="header">
  <h1><span class="logo">Empire AI</span> SEO Audit Report</h1>
  <div class="meta">{{ niche|title }} · {{ metro }} · {{ date }}</div>
</div>

<div style="text-align: center;">
  <div class="score-box">{{ score }}<div class="grade">Grade {{ grade }}</div></div>
  <p><strong>{{ url }}</strong></p>
</div>

<section>
  <h2>Executive Summary</h2>
  <p>{{ summary }}</p>
</section>

<section>
  <h2>Check Results</h2>
  <div class="check-grid">
    {% for category, checks in checks.items() %}
      {% for name, result in checks.items() %}
        <div class="check-item">
          <div class="check-label">{{ category }}: {{ name }}</div>
          <div class="check-value">{{ result }}</div>
        </div>
      {% endfor %}
    {% endfor %}
  </div>
</section>

<section>
  <h2>Top 3 Fixes (Prioritized)</h2>
  {% for i, fix in enumerate(fixes, 1) %}
    <div class="fix">
      <h3>{{ i }}. {{ fix.title }}</h3>
      <p>{{ fix.description }}</p>
      <p><strong>Impact:</strong> {{ fix.impact }} | <strong>Effort:</strong> {{ fix.effort }}</p>
      {% if fix.steps %}
        <ol>
        {% for step in fix.steps %}
          <li>{{ step }}</li>
        {% endfor %}
        </ol>
      {% endif %}
    </div>
  {% endfor %}
</section>

<section>
  <h2>Next Steps</h2>
  <p>{{ cta }}</p>
</section>

<div class="footer">
  Generated by Empire AI · {{ date }} · <a href="https://empire-ai.co.uk">empire-ai.co.uk</a>
</div>
</body>
</html>"""

_env: Optional[Environment] = None

def _get_env() -> Environment:
    global _env
    if _env is None:
        # Write default template if not exists
        tmpl_path = TEMPLATE_DIR / "report.html.j2"
        if not tmpl_path.exists():
            tmpl_path.write_text(DEFAULT_TEMPLATE)
        _env = Environment(
            loader=FileSystemLoader(str(TEMPLATE_DIR)),
            autoescape=select_autoescape(["html", "xml"]),
        )
    return _env

def _score_color(score: int) -> str:
    if score >= 90: return "#1e7e34"      # dark green
    if score >= 80: return "#2e7d32"      # green
    if score >= 70: return "#f57f17"      # amber
    if score >= 60: return "#ef6c00"      # orange
    return "#c62828"                       # red

def _build_context(audit: Dict[str, Any]) -> Dict[str, Any]:
    """Transform audit result into template context."""
    checks = audit.get("checks", {})
    score = audit.get("score", 0)
    grade = audit.get("grade", "F")
    
    # Flatten checks for template
    flat_checks = {}
    for cat, cat_checks in checks.items():
        if isinstance(cat_checks, dict) and "error" not in cat_checks:
            for k, v in cat_checks.items():
                if not k.startswith("_"):
                    flat_checks.setdefault(cat, {})[k.replace("_", " ").title()] = v
    
    # Generate 3 prioritized fixes from checks
    fixes = _generate_fixes(checks, score)
    
    # Summary text
    summary = _generate_summary(score, grade, checks)
    
    # CTA
    cta = "Ready to fix these issues? Start a $10 trial — we'll implement the top fixes and monitor weekly. <a href='https://empire-ai.co.uk/buy-leads'>Get Started</a>"
    
    return {
        "url": audit.get("url", ""),
        "niche": audit.get("niche", ""),
        "metro": audit.get("metro", ""),
        "date": datetime.now(timezone.utc).strftime("%B %d, %Y"),
        "score": score,
        "grade": grade,
        "score_color": _score_color(score),
        "checks": flat_checks,
        "fixes": fixes,
        "summary": summary,
        "cta": cta,
    }

def _generate_summary(score: int, grade: str, checks: Dict) -> str:
    onpage = checks.get("onpage", {})
    tech = checks.get("tech", {})
    psi = checks.get("psi", {})
    
    parts = []
    parts.append(f"Your site scored <strong>{score}/100 (Grade {grade})</strong>.")
    
    if onpage and "error" not in onpage:
        title_ok = onpage.get("title_len", 0) and 30 <= onpage.get("title_len", 0) <= 60
        h1_ok = onpage.get("h1_count", 0) == 1
        meta_ok = onpage.get("meta_desc_len", 0) and 120 <= onpage.get("meta_desc_len", 0) <= 160
        schema_ok = onpage.get("has_schema", False)
        ok_count = sum([title_ok, h1_ok, meta_ok, schema_ok])
        parts.append(f"On-page SEO: {ok_count}/4 fundamentals passing.")
    
    if tech and "error" not in tech:
        ssl = "✅" if tech.get("ssl") else "❌"
        hsts = "✅" if tech.get("hsts") else "❌"
        sitemap = "✅" if tech.get("sitemap_xml") else "❌"
        robots = "✅" if tech.get("robots_txt") else "❌"
        parts.append(f"Technical: SSL {ssl} · HSTS {hsts} · Sitemap {sitemap} · Robots.txt {robots}.")
    
    if psi and "skipped" not in psi:
        perf = psi.get("performance_score", "?")
        parts.append(f"Core Web Vitals (mobile): Performance {perf}/100.")
    
    return " ".join(parts)

def _generate_fixes(checks: Dict, score: int) -> list:
    """Generate 3 prioritized, actionable fixes from audit results."""
    fixes = []
    onpage = checks.get("onpage", {})
    tech = checks.get("tech", {})
    psi = checks.get("psi", {})
    
    # Fix 1: On-page fundamentals
    if onpage and "error" not in onpage:
        title_len = onpage.get("title_len", 0)
        h1_count = onpage.get("h1_count", 0)
        meta_len = onpage.get("meta_desc_len", 0)
        has_schema = onpage.get("has_schema", False)
        
        issues = []
        if not (30 <= title_len <= 60):
            issues.append("title tag length")
        if h1_count != 1:
            issues.append("H1 count")
        if not (120 <= meta_len <= 160):
            issues.append("meta description length")
        if not has_schema:
            issues.append("Schema.org markup")
        
        if issues:
            fixes.append({
                "title": "Fix On-Page SEO Fundamentals",
                "description": f"Your page has issues with: {', '.join(issues)}. These are the highest-impact, lowest-effort fixes for search visibility.",
                "impact": "High",
                "effort": "Low (15-30 min)",
                "steps": [
                    "Set title tag to 30-60 chars with primary keyword near start",
                    "Ensure exactly one H1 matching page topic",
                    "Write meta description 120-160 chars with call-to-action",
                    "Add LocalBusiness/Service Schema.org JSON-LD",
                ]
            })
    
    # Fix 2: Technical basics
    if tech and "error" not in tech:
        missing = []
        if not tech.get("ssl"): missing.append("HTTPS/SSL")
        if not tech.get("hsts"): missing.append("HSTS header")
        if not tech.get("sitemap_xml"): missing.append("sitemap.xml")
        if not tech.get("robots_txt"): missing.append("robots.txt")
        if not tech.get("gzip"): missing.append("Gzip/Brotli compression")
        
        if missing:
            fixes.append({
                "title": "Enable Missing Technical Foundations",
                "description": f"Missing: {', '.join(missing)}. These affect crawlability, security, and Core Web Vitals.",
                "impact": "Medium-High",
                "effort": "Low-Medium (30-60 min)",
                "steps": [
                    "Install SSL cert (Let's Encrypt) and force HTTPS",
                    "Add Strict-Transport-Security header (max-age=31536000)",
                    "Generate sitemap.xml and submit to GSC",
                    "Create robots.txt with sitemap reference",
                    "Enable Brotli/Gzip in nginx/Apache/Caddy",
                ]
            })
    
    # Fix 3: Core Web Vitals
    if psi and "skipped" not in psi:
        lcp = psi.get("largest_contentful_paint")
        inp = psi.get("interaction_to_next_paint")
        cls = psi.get("cumulative_layout_shift")
        perf = psi.get("performance_score", 0)
        
        if perf < 70 or (lcp and lcp > 2500) or (inp and inp > 200) or (cls and cls > 0.1):
            fixes.append({
                "title": "Improve Core Web Vitals",
                "description": f"Performance score: {perf}/100. LCP: {lcp or '?'}ms · INP: {inp or '?'}ms · CLS: {cls or '?'}. Slow loading kills conversions.",
                "impact": "High",
                "effort": "Medium-High (1-4 hrs)",
                "steps": [
                    "Optimize images: WebP, proper dimensions, lazy loading",
                    "Eliminate render-blocking CSS/JS (defer, inline critical)",
                    "Preload LCP image, use fetchpriority=high",
                    "Reduce JavaScript execution time (code-split, remove unused)",
                    "Set explicit width/height on images to prevent CLS",
                    "Use CDN with edge caching",
                ]
            })
    
    # Fallback generic fixes if we have < 3
    generic_fixes = [
        {
            "title": "Build Local Citation Profile",
            "description": "Consistent NAP (Name, Address, Phone) across 50+ directories boosts local pack rankings.",
            "impact": "Medium",
            "effort": "Medium (2-4 hrs)",
            "steps": ["Audit current citations (BrightLocal/Whitespark)", "Fix NAP inconsistencies", "Submit to top 50 directories", "Claim/optimize Google Business Profile"],
        },
        {
            "title": "Add FAQ Schema for Zero-Click Visibility",
            "description": "FAQ schema makes your page eligible for 'People Also Ask' and featured snippets.",
            "impact": "Medium",
            "effort": "Low (30 min)",
            "steps": ["Identify 5-10 common customer questions", "Add FAQPage JSON-LD with questions/answers", "Test in Rich Results Test", "Monitor GSC for FAQ impressions"],
        },
        {
            "title": "Set Up Review Generation System",
            "description": "Review velocity + rating directly impact local pack ranking and conversion rate.",
            "impact": "High",
            "effort": "Low (setup) + Ongoing",
            "steps": ["Add review link to email signature/SMS", "Automate post-job review request", "Respond to all reviews within 24h", "Showcase best reviews on site with schema"],
        },
    ]
    
    for gf in generic_fixes:
        if len(fixes) >= 3:
            break
        fixes.append(gf)
    
    return fixes[:3]

def generate_pdf(audit: Dict[str, Any], output_path: Optional[str] = None) -> str:
    """
    Generate branded PDF from audit result.
    Returns path to generated PDF.
    """
    ctx = _build_context(audit)
    env = _get_env()
    template = env.get_template("report.html.j2")
    html = template.render(**ctx)
    
    if output_path is None:
        fd, output_path = tempfile.mkstemp(suffix=".pdf", prefix="empire_audit_")
        os.close(fd)
    
    # Generate PDF
    HTML(string=html, base_url=str(TEMPLATE_DIR)).write_pdf(
        output_path,
        stylesheets=[CSS(string="@page { size: A4; margin: 2cm; }")]
    )
    
    return output_path

def generate_html(audit: Dict[str, Any]) -> str:
    """Generate HTML string for preview/email."""
    ctx = _build_context(audit)
    env = _get_env()
    template = env.get_template("report.html.j2")
    return template.render(**ctx)

# CLI for testing
if __name__ == "__main__":
    import json, sys
    
    test_audit = {
        "url": "https://example.com",
        "niche": "plumbing",
        "metro": "NYC",
        "score": 67,
        "grade": "D",
        "checks": {
            "onpage": {"title_len": 65, "h1_count": 2, "meta_desc_len": 0, "has_schema": False},
            "tech": {"ssl": True, "hsts": False, "sitemap_xml": False, "robots_txt": True, "gzip": True},
            "psi": {"performance_score": 42, "largest_contentful_paint": 4200, "interaction_to_next_paint": 380, "cumulative_layout_shift": 0.25},
        }
    }
    
    if len(sys.argv) > 1:
        test_audit = json.loads(sys.argv[1])
    
    pdf_path = generate_pdf(test_audit)
    print(f"Generated: {pdf_path}")