"""Evidence-preserving Phase 4 Buyer Acquisition Scout.

Executes bounded research queries generated by Buyer Acquisition Team, discovers
domains through Empire Search Fabric, probes first-party sites, and writes a
runtime evidence artifact.

It does not create buyers/prospects, send outreach, accept terms, or write to
Supabase. A discovered company is a research candidate only until reconciled
through canonical identity/review flows.
"""
from __future__ import annotations

from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import urlparse

from empire_os.buyer_acquisition_team import direct_buyer_profile
from empire_os.icp_buyer_trigger_intelligence import (
    assess_icp_candidate,
)
from empire_os.search_fabric.search import search_domains_parallel
from empire_os.search_fabric.site_probe import probe_site


OUTPUT = Path("runtime/buyer_acquisition/scout_latest.json")


def _host(value: str) -> str:
    text = str(value or "").strip().lower()
    if not text:
        return ""
    parsed = urlparse(
        text if "://" in text else "https://" + text
    )
    host = parsed.netloc.split("@")[-1].split(":")[0]
    return host[4:] if host.startswith("www.") else host


def collect_research_queries(
    plan: Mapping[str, Any],
    *,
    max_queries: int = 30,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for target_kind, targets in (
        ("corridor", plan.get("priority_targets") or []),
        ("product", plan.get("product_priority_targets") or []),
        ("icp", plan.get("icp_priority_targets") or []),
    ):
        for target in targets:
            if not isinstance(target, Mapping):
                continue
            query_groups = target.get("research_queries")
            if not isinstance(query_groups, Mapping):
                continue
            for pool, queries in query_groups.items():
                if not isinstance(queries, list):
                    continue
                for query in queries:
                    text = str(query or "").strip()
                    if not text:
                        continue
                    rows.append({
                        "query": text,
                        "buyer_pool": str(pool),
                        "target_kind": target_kind,
                        "corridor_key": target.get("corridor_key"),
                        "product_code": target.get("product_code"),
                        "icp_profile_key": target.get("icp_profile_key"),
                        "buying_triggers": list(
                            target.get("buying_triggers") or []
                        ),
                        "decision_maker_roles": list(
                            target.get("decision_maker_roles") or []
                        ),
                        "priority_score": int(
                            target.get("priority_score") or 0
                        ),
                    })

    rows.sort(
        key=lambda row: (
            -int(row["priority_score"]),
            str(row["target_kind"]),
            str(row["query"]),
        )
    )

    dedup: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for row in rows:
        key = (row["query"], row["buyer_pool"])
        if key in seen:
            continue
        seen.add(key)
        dedup.append(row)
        if len(dedup) >= max(1, min(max_queries, 100)):
            break
    return dedup


def run_buyer_scout(
    plan: Mapping[str, Any],
    *,
    max_queries: int = 30,
    results_per_query: int = 8,
    max_domains: int = 40,
    max_probes: int = 20,
) -> dict[str, Any]:
    queries = collect_research_queries(
        plan,
        max_queries=max_queries,
    )
    query_text = [row["query"] for row in queries]

    domain_map = (
        search_domains_parallel(
            query_text,
            num=max(1, min(results_per_query, 20)),
        )
        if query_text
        else {}
    )

    provenance: dict[str, list[dict[str, Any]]] = {}
    for row in queries:
        for domain in domain_map.get(row["query"], []):
            host = _host(domain)
            if not host:
                continue
            provenance.setdefault(host, []).append({
                "query": row["query"],
                "buyer_pool": row["buyer_pool"],
                "target_kind": row["target_kind"],
                "corridor_key": row.get("corridor_key"),
                "product_code": row.get("product_code"),
                "icp_profile_key": row.get("icp_profile_key"),
                "buying_triggers": list(
                    row.get("buying_triggers") or []
                ),
                "decision_maker_roles": list(
                    row.get("decision_maker_roles") or []
                ),
            })

    ranked_domains = sorted(
        provenance,
        key=lambda domain: (
            -len(provenance[domain]),
            domain,
        ),
    )[:max(1, min(max_domains, 200))]

    candidates: list[dict[str, Any]] = []
    probe_failures: Counter[str] = Counter()
    probe_domains = ranked_domains[:max(1, min(max_probes, 100))]

    def _probe(domain: str) -> tuple[str, dict[str, Any]]:
        return domain, probe_site(
            "https://" + domain,
            max_pages=4,
            request_timeout=5.0,
            time_budget_seconds=12.0,
        )

    probe_results: dict[str, dict[str, Any]] = {}
    workers = max(1, min(5, len(probe_domains)))
    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {
            executor.submit(_probe, domain): domain
            for domain in probe_domains
        }
        for future in as_completed(futures):
            domain = futures[future]
            try:
                _, evidence = future.result()
            except Exception as exc:
                probe_failures[type(exc).__name__] += 1
                continue
            probe_results[domain] = evidence

    for domain in probe_domains:
        evidence = probe_results.get(domain) or {}
        if evidence.get("ok") is not True:
            probe_failures[
                str(evidence.get("error") or "site_probe_failed")
            ] += 1
            continue

        business_names = [
            str(value).strip()
            for value in (evidence.get("business_names") or [])
            if str(value).strip()
        ]
        record = {
            "business_name": (
                business_names[0]
                if business_names
                else evidence.get("title")
            ),
            "business_name_source": (
                "first_party_business_name"
                if business_names
                else "page_title_fallback"
            ),
            "site_business_names": business_names[:10],
            "website": evidence.get("canonical_url")
            or evidence.get("final_url"),
            "description": evidence.get("description"),
            "notes": " ".join(
                str(page.get("visible_text") or "")[:1500]
                for page in (evidence.get("pages_checked") or [])[:2]
                if isinstance(page, Mapping)
            ),
        }
        profile = direct_buyer_profile(record)

        pools = sorted({
            str(item.get("buyer_pool") or "")
            for item in provenance[domain]
            if str(item.get("buyer_pool") or "")
        })
        products = sorted({
            str(item.get("product_code") or "")
            for item in provenance[domain]
            if str(item.get("product_code") or "")
        })
        corridors = sorted({
            str(item.get("corridor_key") or "")
            for item in provenance[domain]
            if str(item.get("corridor_key") or "")
        })
        icp_profiles = sorted({
            str(item.get("icp_profile_key") or "")
            for item in provenance[domain]
            if str(item.get("icp_profile_key") or "")
        })
        icp = assess_icp_candidate(
            {
                **record,
                "buyer_type": profile["buyer_type"],
                "direct_signal_hits": profile["direct_signal_hits"],
                "reseller_signal_hits": profile["reseller_signal_hits"],
                "target_buyer_pools": pools,
                "target_product_codes": products,
                "first_party_people": list(
                    evidence.get("people") or []
                )[:10],
            },
            target_profile_keys=icp_profiles,
        )

        candidates.append({
            "domain": domain,
            "business_name": record["business_name"],
            "business_name_source": record["business_name_source"],
            "site_business_names": record["site_business_names"],
            "website": record["website"],
            "description": record["description"],
            "first_party_emails": list(
                evidence.get("emails") or []
            )[:10],
            "first_party_phones": list(
                evidence.get("phones") or []
            )[:10],
            "first_party_people": [
                dict(person)
                for person in (evidence.get("people") or [])[:10]
                if isinstance(person, Mapping)
            ],
            "buyer_type": profile["buyer_type"],
            "direct_buyer_score": profile["direct_buyer_score"],
            "explicit_direct_buyer_evidence": profile[
                "explicit_direct_buyer_evidence"
            ],
            "direct_signal_hits": profile["direct_signal_hits"],
            "reseller_signal_hits": profile["reseller_signal_hits"],
            "target_buyer_pools": pools,
            "target_product_codes": products,
            "target_corridor_keys": corridors,
            "target_icp_profile_keys": icp_profiles,
            "icp_intelligence": icp,
            "observed_buying_triggers": list(
                icp.get("observed_buying_triggers") or []
            ),
            "why_now_state": icp.get("why_now_state"),
            "decision_maker_state": icp.get(
                "decision_maker_state"
            ),
            "economic_capacity_state": icp.get(
                "economic_capacity_state"
            ),
            "budget_verified": False,
            "query_evidence_count": len(provenance[domain]),
            "query_evidence": provenance[domain],
            "site_evidence_score": evidence.get("evidence_score"),
            "first_party_email_count": len(evidence.get("emails") or []),
            "first_party_phone_count": len(evidence.get("phones") or []),
            "people_count": len(evidence.get("people") or []),
            "candidate_state": "RESEARCH_EVIDENCE_ONLY",
            "canonical_identity_verified": False,
            "commercial_terms_verified": False,
            "outreach_authorized": False,
        })

    candidates.sort(
        key=lambda row: (
            -int(row["direct_buyer_score"]),
            -int(row["query_evidence_count"]),
            -float(row.get("site_evidence_score") or 0.0),
            str(row["domain"]),
        )
    )

    return {
        "schema_version": "empire.buyer_acquisition_scout.v1",
        "mode": "OBSERVE",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "query_count": len(queries),
        "domain_count": len(ranked_domains),
        "probed_domain_count": min(len(ranked_domains), max_probes),
        "candidate_count": len(candidates),
        "explicit_direct_buyer_candidate_count": sum(
            row["explicit_direct_buyer_evidence"]
            for row in candidates
        ),
        "icp_assessed_candidate_count": sum(
            bool(
                (row.get("icp_intelligence") or {}).get(
                    "best_profile_key"
                )
            )
            for row in candidates
        ),
        "observed_trigger_candidate_count": sum(
            row.get("why_now_state") == "OBSERVED_TRIGGER"
            for row in candidates
        ),
        "decision_maker_role_match_count": sum(
            row.get("decision_maker_state") == "OBSERVED_ROLE_MATCH"
            for row in candidates
        ),
        "economic_capacity_proxy_count": sum(
            row.get("economic_capacity_state") == "OBSERVED_PROXY"
            for row in candidates
        ),
        "verified_budget_candidate_count": 0,
        "probe_failure_counts": dict(sorted(probe_failures.items())),
        "queries": queries,
        "candidates": candidates,
        "database_write_performed": False,
        "outbound_sent": False,
        "terms_accepted": False,
        "actual_revenue": False,
        "execution_authority": "none",
    }


def refresh_buyer_scout(
    repo_root: str | Path,
    **kwargs: Any,
) -> dict[str, Any]:
    root = Path(repo_root).resolve()
    plan_path = root / "runtime/buyer_acquisition/latest.json"
    try:
        plan = json.loads(plan_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        plan = {}
    if not isinstance(plan, dict):
        plan = {}

    payload = run_buyer_scout(plan, **kwargs)
    path = root / OUTPUT
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    tmp.replace(path)
    return payload
