#!/usr/bin/env python3
"""Empire OS long-form (8-15 min) YouTube explainer builder.

Free, local, CPU-only. Produces a branded long-form video from a topic:
  intro (branded) + [section title card + face-loop segment] x N + outro (branded)
with a persistent watermark. Voice = edge-tts (free). Face = portrait (free
randomuser source) + Ken Burns loop. No paid APIs, no branding assets needed.

The script is generated by the LLM as 6-10 spoken sections so the result runs
8-15 minutes. Each section gets a title card so a static face-loop stays
watchable.

QC: video_qc.judge(mode="longform") accepts title-card segments (no face) and
only hard-fails on silent audio / wrong format / zero face across ALL body.
"""
from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, "/root/empire_os")

from empire_os import avatar_pipeline as av
from empire_os import video_brand as brand
from empire_os import social_syndication as syn

RENDER_DIR = Path("/root/empire_os/empire_os/social_render")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FPS = 30
TITLE_CARD_SEC = 3.0
TARGET_SEC = 600  # ~10 min; sections sized to land 8-15 min


def write_outline(topic: str, n_sections: int = 8) -> dict:
    """LLM -> structured long-form outline (sections with spoken scripts)."""
    prompt = f"""You are a YouTube scriptwriter for Empire OS, an AI agent
platform that automates lead-gen and closes deals on autopilot.
Write a LONG-FORM ({TARGET_SEC//60}-minute) explanatory YouTube video about:
{topic}.

Structure it as {n_sections} spoken SECTIONS. Each section: a punchy title and
a spoken paragraph of 90-140 words (conversational, founder-energy, hooks the
viewer, gives a concrete takeaway). Open section 1 with a direct answer to the
topic. End the last section with a subscribe/follow CTA.

Return STRICT JSON only:
{{
  "title": "YouTube title (question or bold claim)",
  "hook": "first 1-2 sentence attention grabber (spoken)",
  "sections": [
    {{"title": "Section 1 title", "script": "90-140 word spoken paragraph"}},
    ...
  ],
  "cta": "subscribe / follow call to action (spoken)"
}}
No markdown, no commentary outside the JSON."""
    text = syn._llm([{"role": "user", "content": prompt}])
    if text.startswith("__ERR__"):
        return {"error": f"LLM failed: {text[7:]}"}
    s, e = text.find("{"), text.rfind("}") + 1
    if s < 0 or e <= s:
        return {"error": "no JSON in outline", "raw": text[:200]}
    blob = text[s:e].replace("```json", "").replace("```", "")
    try:
        return json.loads(blob)
    except Exception as je:
        return {"error": f"outline parse failed: {je}", "raw": blob[:200]}


def _voice_section(text: str, wav: str) -> float:
    """TTS one section; return its spoken duration (sec)."""
    engine = av.tts(text, wav)
    if engine == "failed":
        return 0.0
    try:
        d = subprocess.run(["ffprobe", "-v", "error", "-show_entries",
                            "format=duration", "-of", "default=nw=1:nk=1", wav],
                           capture_output=True, text=True, timeout=20).stdout.strip()
        return float(d) if d else 0.0
    except Exception:
        return 0.0


def _title_card(title: str, out_mp4: str, dur: float = TITLE_CARD_SEC) -> bool:
    """Branded section title card (animated text on dark bg, accent color)."""
    col = brand.BRAND["color"]
    bg = brand.BRAND["bg"]
    vf = (
        f"color=c=0x{bg}:s=1280x720:r={FPS},format=yuv420p,"
        f"drawtext=fontfile='{FONT}':text='{title[:42]}':fontcolor=0x{col}:"
        f"fontsize=58:box=1:boxcolor=black@0.6:"
        f"x=(w-text_w)/2:y=(h-text_h)/2:"
        f"alpha='if(lt(t,0.4),0,if(lt(t,1.0),(t-0.4)/0.6,1))'"
    )
    r = subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", vf,
                        "-t", str(dur), "-c:v", "libx264",
                        "-pix_fmt", "yuv420p", out_mp4],
                       capture_output=True, text=True, timeout=60)
    return r.returncode == 0


def build(topic: str, out_mp4: str, n_sections: int = 8) -> dict:
    """Full long-form build. Returns {ok, out, sections, duration, ...}."""
    out = Path(out_mp4)
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.gettempdir()) / "lf"
    tmp.mkdir(exist_ok=True)

    outline = write_outline(topic, n_sections)
    if "error" in outline:
        return {"ok": False, "error": outline["error"]}
    sections = outline.get("sections", [])
    if not sections:
        return {"ok": False, "error": "no sections in outline"}

    # per-section: voice -> face-loop segment -> title card -> pair
    body_parts = []  # ordered mp4 paths for concat
    sec_meta = []
    for i, sec in enumerate(sections):
        wav = str(tmp / f"sec{i}.wav")
        dur = _voice_section(sec.get("script", ""), wav)
        if dur <= 0:
            continue
        seg = str(tmp / f"face{i}.mp4")
        mode = av.talking_head(wav, seg)
        if mode == "failed":
            continue
        card = str(tmp / f"card{i}.mp4")
        if not _title_card(sec.get("title", f"Part {i+1}"), card):
            card = None
        if card:
            body_parts.append(card)
        body_parts.append(seg)
        sec_meta.append({"title": sec.get("title"), "dur": round(dur, 1),
                         "face_mode": mode})

    if not body_parts:
        return {"ok": False, "error": "no sections rendered"}

    # concat body
    body_list = tmp / "body_list.txt"
    body_list.write_text("\n".join(f"file '{p}'" for p in body_parts) + "\n")
    body_mp4 = str(tmp / "body.mp4")
    r = subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0",
                        "-i", str(body_list), "-vsync", "vfr",
                        "-c:v", "libx264", "-pix_fmt", "yuv420p",
                        "-c:a", "aac", "-b:a", "128k", body_mp4],
                       capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        return {"ok": False, "error": "body concat failed",
                "detail": r.stderr[-200:]}

    # branded intro + body + outro
    final = brand.assemble(body_mp4, str(out))
    try:
        dur = float(subprocess.run(["ffprobe", "-v", "error",
                    "-show_entries", "format=duration",
                    "-of", "default=nw=1:nk=1", final],
                    capture_output=True, text=True, timeout=20).stdout.strip())
    except Exception:
        dur = 0.0

    return {
        "ok": True,
        "out": str(out),
        "title": outline.get("title"),
        "hook": outline.get("hook"),
        "cta": outline.get("cta"),
        "sections": len(sec_meta),
        "section_meta": sec_meta,
        "duration": round(dur, 1),
        "voice_engine": "edge-tts",
        "face_mode": "kenburns",
    }


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Empire OS long-form builder")
    ap.add_argument("--topic", required=True)
    ap.add_argument("--out", default=str(RENDER_DIR / "longform_test.mp4"))
    ap.add_argument("--sections", type=int, default=8)
    a = ap.parse_args()
    res = build(a.topic, a.out, a.sections)
    print(json.dumps(res, default=str, indent=2))
