"""Compatibility boundary between Omega 2.0 and legacy consumers.

Omega 2.0 is the source of intelligence. Legacy consumers may continue to
receive the established omega_score / omega_tier fields without knowing about
the new prediction contract.
"""

from __future__ import annotations

from typing import Any, Mapping

from .omega import OmegaPrediction, analyze


def analyze_lead(lead: Mapping[str, Any]) -> OmegaPrediction:
    """Run the canonical Omega 2.0 analysis for a lead."""
    return analyze(lead)


def legacy_fields(lead: Mapping[str, Any]) -> dict[str, Any]:
    """Return legacy-compatible score fields derived from Omega 2.0.

    The caller's existing omega_score is never used as an input to the new
    prediction. The returned score/tier are generated by Omega 2.0 so legacy
    storage and consumers can continue operating.
    """
    prediction = analyze_lead(lead)
    return {
        "omega_score": prediction.legacy_omega_score,
        "omega_tier": prediction.legacy_omega_tier,
    }


def analyze_with_legacy_fields(
    lead: Mapping[str, Any],
) -> tuple[OmegaPrediction, dict[str, Any]]:
    """Return the canonical prediction and legacy-compatible fields."""
    prediction = analyze_lead(lead)
    return prediction, {
        "omega_score": prediction.legacy_omega_score,
        "omega_tier": prediction.legacy_omega_tier,
    }
